<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project default="java" name="TP10">
    <!--this file was created by Eclipse Runnable JAR Export Wizard-->
    <!--ANT 1.7 is required                                        -->
    <!--define folder properties-->
    <property name="dir.buildfile" value="."/>
    <property name="dir.workspace" value="${dir.buildfile}"/>
    <property name="dir.jarfile" value="${dir.workspace}/Archives"/>
    <property name="src_dir" value="src"/>
    <property name="bin_dir" value="bin"/>
    <property name="javadoc.dir" value="doc"/>

    <target name="javadoc">
        <mkdir dir="${javadoc.dir}"/>
        <javadoc sourcepath="${src_dir}" destdir="${javadoc.dir}" author="true" version="true" use="true" 
                 windowtitle="Documentation TP10" doctitle="Documentation TP10">
            <fileset dir="${src_dir}">
                <include name="**/*.java"/>
            </fileset>
        </javadoc>
    </target>

    <target name="delete">
        <delete>
            <fileset dir="${bin_dir}">
                <include name="**/*.class"/>
            </fileset>
        </delete>
    </target>

    <target name="mkdir" depends="delete">
        <mkdir dir="${bin_dir}"/>
    </target>

    <target name="javac" depends="mkdir">
        <echo message="Compilation des fichiers sources..."/>
        <javac srcdir="${src_dir}" destdir="${bin_dir}" debug="on"/>
    </target>

    <target name="mkdir-jar-dir">
        <mkdir dir="${dir.jarfile}"/>
    </target>

    <target name="jar" depends="mkdir-jar-dir,javac">
        <jar destfile="${dir.jarfile}/TP10.jar" filesetmanifest="mergewithoutmain">
            <manifest>
                <attribute name="Main-Class" value="paires.TestPaire"/>
                <attribute name="Class-Path" value="."/>
            </manifest>
            <fileset dir="${bin_dir}"/>
        </jar>
    </target>

    <target name="java" depends="jar">
        <java jar="${dir.jarfile}/TP10.jar" fork="true"/>
    </target>
</project>
