<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project default="java" name="Create Runnable Jar for Project TP1">
    <!--this file was created by Eclipse Runnable JAR Export Wizard-->
    <!--ANT 1.7 is required                                        -->
    <!--define folder properties-->
    <property name="dir.buildfile" value="."/>
    <property name="dir.workspace" value="${dir.buildfile}"/>
    <property name="dir.jarfile" value="${dir.workspace}/Archives"/>
	<property name="src_dir" value="src"></property>
	<property name="bin_dir" value="bin"></property>
		
	
	<target name="delete">
		<delete dir="${bin_dir}"></delete>
	</target>
	
	<target name="mkdir" depends="delete">
			<mkdir dir="${bin_dir}"></mkdir>
	</target>
	

	
	<target name="javac" depends="mkdir">
		<echo message="Compilation des fichiers sources..."/>
		<javac srcdir="${src_dir}"
         destdir="${bin_dir}"
         classpath="${dir.jarfile}"
         debug="on"
	/>
	</target>
	
	
    <target name="jar" depends="javac">
        
        <jar destfile="${dir.jarfile}/hellopaul.jar" filesetmanifest="mergewithoutmain">
            <manifest>
                <attribute name="Main-Class" value="HelloWorld"/>
                <attribute name="Class-Path" value="."/>
            </manifest>
            <fileset dir="${bin_dir}"/>
        </jar>
    </target>
	
	
	<target name="java" depends="jar">
		<java jar="${dir.jarfile}/hellopaul.jar" fork="true"/>
	</target>
	
	
	
		
	
</project>